### ISSUE TITLE
"Invalid Date" being displayed in feature card

### ISSUE THREAD

**Issue by GitPuffy** [yariplus/nodebb-plugin-featured-topics-extended#13]
In NodeBB `v1.4.2` the words `Invalid Date` are being displayed on the feature card after the post title

**Comment by GitPuffy** [comment]
This change did not resolve my problem.   When using the "Featured Topic Cards" widget `Invalid Date` is still being displayed.

![image](https://cloud.githubusercontent.com/assets/16783602/21855359/750c4afc-d7db-11e6-9ced-5b604bef5fb1.png)

**Comment by yariplus** [comment]
doh. My bad.

**Comment by yariplus** [comment]
Try the new version

**Comment by GitPuffy** [comment]
It works!  Thanks, problem seems resolved now.
