### ISSUE TITLE
Only Show Pagination if more than one site

### ISSUE THREAD

**Issue by DeusProx** [yariplus/nodebb-plugin-featured-topics-extended#17]
I use it as a admin-blog in front of our forum and have only one post atm. So i don't want the pagenav to show when i don't have a second side. It's confusing

**Comment by yariplus** [comment]
Sounds good to me! Do you have a pull request?

**Comment by DeusProx** [comment]
ATM not. It's more a feature request but If you don't have time I would implement it next week on my own.

**Comment by DeusProx** [comment]
Thank you! I completely forgot about this!
