### ISSUE TITLE
Only works on news list, creating a new list shows blank.

### ISSUE THREAD

**Issue by ghost** [yariplus/nodebb-plugin-featured-topics-extended#18]
Only works on news list, creating a new list shows blank. Via the ACP. create a new list, and put featured topic in it, displays as blank, if I do the same using the default news list it works. It appears limited from that point of view.

**Comment by yariplus** [comment]
What version of NodeBB?

**Comment by yariplus** [comment]
Everything appears to be working as intended.

Please reopen if you have more information on how you think it should work.
