### ISSUE TITLE
The "Continue Reading" always gets displayed at the end of the entire topic.

### ISSUE THREAD

**Issue by ghost** [yariplus/nodebb-plugin-featured-topics-extended#19]
The "Continue Reading" always gets displayed at the end of the entire topic. At present not much use in having the Continue Reading if it displays the entire topic anyway,  this would be really good it it stopping after so many lines of text, and clicking it forces the user to register to read the rest of it. That way I can promote more users to my site.

**Comment by aribuga** [comment]
![image](https://user-images.githubusercontent.com/15672497/26874682-269d6f3e-4b87-11e7-9d78-14574b23487e.png)

big problem :/

**Comment by yariplus** [comment]
I'm not quite sure of the best way to fix this. I never meant to show the whole topic, so I am looking for a solution.

Giving a fixed height looks bad. Applying a CSS fade could make at a bit better.

I could limit the amount of `<p>` tags.

Some sort of calculation could be done. Characters or words per `<p>` tag.

Open to suggestions.

**Comment by ghost** [comment]
Maybe limit view to 280 characters and then show continue reading?

**Comment by yariplus** [comment]
Characters works for me, added in 0.4.2
