### ISSUE TITLE
[Bug] Incorrect links when initially loaded from the index page

### ISSUE THREAD

**Issue by artch** [yariplus/nodebb-plugin-featured-topics-extended#24]
Cards widget contains links with raw `%7Bconfig.relative_path%7D` part which prevents them from working. It only works when navigated somewhere after initial load.

Reproduce scenario:

1. Go to https://screeps.com/forum/
2. Click any featured topic in the top.
3. You will be redirected to a URL like this:
```
https://screeps.com/forum/%7Bconfig.relative_path%7D/topic/1893/tournament-botarena-pure-ai-battle-royale
```
Obviously, it throws a `Not Found` error.
4. Click the Categories menu icon in the top;
5. Click any featured topic again. Now it works.

**Comment by yariplus** [comment]
Hey, it's screeps! Thanks for info. I'll get that patched tonight.

**Comment by yariplus** [comment]
Could you test the recently pushed version 0.3.1 ?

**Comment by artch** [comment]
Works like a charm now, thanks!
