### ISSUE TITLE
Featured topics list from category don't show in widgets

### ISSUE THREAD

**Issue by jffz** [yariplus/nodebb-plugin-featured-topics-extended#27]
As the title said, this looks to not works here.

Triied to create numerous topics after featuring the category.

NodeBB v1.5.3.

**Comment by yariplus** [comment]
Investigating

**Comment by yariplus** [comment]
Seems to work for me, but it's a bit finicky. It resets the widget settings every time you go to the widget page. I think that's what's causing your issue.

**Comment by yariplus** [comment]
Everything seems to be working now. lmk
