### ISSUE TITLE
Multiple Featured Topic lists.

### ISSUE THREAD

**Issue by yariplus** [yariplus/nodebb-plugin-featured-topics-extended#3]
Instead of having one list of featured topics, their could be multiple lists/groups. Widget config would have a drop-down to select the group you want to display.

Edit "Feature this Topic" modal to select the featured group or create a new group to add the topic into.

**Comment by exomarty** [comment]
that would be awesome

**Comment by yariplus** [comment]
Fixed in 0.2.0 update
