### ISSUE TITLE
Update to 1.10

### ISSUE THREAD

**Issue by alfazaz** [yariplus/nodebb-plugin-featured-topics-extended#31]
Hello !

Just a message to warn you that it's necessary to update this plugin for nodebb 1.10 (widgets are not working). ;-)

**Comment by alfazaz** [comment]
Or, may be, I'm doing something wrong... I tried also with nodebb 1.9.3, 1.8.2, 1.7.5 from scratch without success (when I want a widget to show news on global header or global sidebar, nothing is shown). Strange...

What are good steps to test featured widgets ?

**Comment by alfazaz** [comment]
Sorry for the multiposts... I found infos on https://community.nodebb.org/topic/9507/nodebb-plugin-featured-topics-extended-feature-topics-in-a-news-blog-page-and-widgets and I have some success on nodebb 1.10.1 now.

If have to work more with your plugin to see if there is any problem on nodebb 1.10.1.

**Comment by yariplus** [comment]
Hey there. Re-opening this. There is actually a number of problems with the widgets on 1.10. I am working on an update to fix, as well as some needed improvements to making lists.

**Comment by alfazaz** [comment]
Ok. I let you work on your interesting plugin and follow its status for my project. Thanks !

**Comment by djensen47** [comment]
Any progress? It looks like the card work fine but the sidebar widget show nothing.

**Comment by osdio** [comment]
Any progress?

**Comment by yariplus** [comment]
Not yet. I've been pretty overwhelmed with life events. I will try to get a new version out by end of month.

**Comment by alfazaz** [comment]
No success with your plugin under nodebb 1.12.0... This is embarrassing because it has great functionalities.

Found the origin of my problem : widgets are not working because when we put one in admin/extend/widget in one zone (header for example), the default value "News" for "Featured Topics List" is not saved in database (slug stays empty). Everything works if I change it to another value, save, and go back to "News" and save again (and rebuild)...

**Comment by alfazaz** [comment]
(Edited because my first try was a bad way...)
I think I found a solution (if I make no mistake) : 

Add an else condition to set slug input default value to news into acp.js :
```
    // Set the select option.
    if (sel.find('[value="' + slug.val() + '"]').length) {
	    sel.val(slug.val());
    } else {
	    // Set default slug value
	    slug.val('news');
    }
```
I'm looking after other bugs (if I have time and skill...).

**Comment by yariplus** [comment]
This should be fixed now. (Although everything is updated to 1.15 compat)
