### ISSUE TITLE
Pictures url error in Scout Template

### ISSUE THREAD

**Issue by alanjinqs** [yariplus/nodebb-plugin-featured-topics-extended#32]
Running at NodeBB v1.10.1
Plugin Version 0.4.3

Template  "Scout", cannot get the picture's URL. It shows Unknown in src tag

`<img src="" alt="Get to know about NodeBB" style="width:100%;max-height:180px;overflow-y:hidden;">
`
![avatar](https://piccdn.freejishu.com/images/2018/09/13/qW0aB.png)

**Comment by yariplus** [comment]
I'll get this fixed with the next release.
