### ISSUE TITLE
Selected news list slug gets saved as "slug-select" instead of "slug" in the widget data, resulting in empty widgets

### ISSUE THREAD

**Issue by AGraber** [yariplus/nodebb-plugin-featured-topics-extended#34]
I found out that the plugin wasn't rendering the topics correctly on NodeBB 1.13. I went and poked through the source code and found out that in the widget data, `slug` remains as `''`, while `slug-select` contains the actual topic list slug. Thus the topics are never found by the plugin and the result is an empty container.

A `console.log(widget.data);` helped me discover this:
```js
{
  slug: '',
  'slug-select': 'news',
  sorted: '',
  max: '5',
  template: 'porta',
  title: 'Hello',
  container: '',
  groups: [],
  groupsHideFrom: []
}
```
The plugin is looking for `slug` and not `'slug-select'` though.

I guess the widget data didn't got overwritten on older installs which probably made this bug go unnoticed. I'm not very experienced in NodeBB so I don't know the desired approach in fixing this but I hope you do it soon.

**Comment by yariplus** [comment]
aaah, yeah, that's cause the default is undefined, so never occurs on existing widgets.
