### ISSUE TITLE
Truncating text causes post content html tags to break

### ISSUE THREAD

**Issue by AGraber** [yariplus/nodebb-plugin-featured-topics-extended#35]
https://github.com/yariplus/nodebb-plugin-featured-topics-extended/blob/7e1646c10e0a60d14d83d2f813934f44ef305aeb/src/lib/plugin.js#L998-L999

This specific part truncates the body's content without any regard of the html tags that might be in there. This can break the layout of the page completely.

A suggestion: `text-clipper` can truncate html without breaking it, I'm currently doing this to fix it temporarily:
```js
const clip = require("text-clipper").default;

// ...

if (topic.post.content.length > charLimit) {
  topic.post.content = clip(topic.post.content, charLimit, {
    breakWords: true,
    indicator: '...',
  });
}
```

If you're OK with adding a dependency, I can make a PR

**Comment by yariplus** [comment]
Works perfect, thanks!
