### ISSUE TITLE
Sidebar links contain {relative_path}

### ISSUE THREAD

**Issue by gdude2002** [yariplus/nodebb-plugin-featured-topics-extended#4]
For example, `https://domain.ext/%7Brelative_path%7D/topic/3/new-forum`

**Comment by gdude2002** [comment]
The "posted" part of each item also has a title of "Invalid date".

**Comment by yariplus** [comment]
Thanks.

Should be fixed now.

/)

**Comment by gdude2002** [comment]
NodeBB/npm aren't finding the new version yet, will report back when they do

**Comment by gdude2002** [comment]
Looks good - thanks for the patch!

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by yariplus** [comment]
Cool. Let me know if you have any other issues or feature requests.

The plugin is still in it's very early stages.
