### ISSUE TITLE
Subfolder links are incorrect

### ISSUE THREAD

**Issue by uyiyei** [yariplus/nodebb-plugin-featured-topics-extended#40]
Hello.

If NodeBB is installed using subfolder, like https://example.com/forum, links to topics on news page are without "/forum/" part, but correct in cards widget.

**Comment by yariplus** [comment]
Thanks! Let me know if it's still an issue. It worked in my tests, but I don't have a real instance in a subdirectory.

**Comment by uyiyei** [comment]
I cloned master branch from github and installed it. It shows that it's of version 0.5.0 (the latest is 0.5.1) and it still doesn't work.

**Comment by uyiyei** [comment]
Ok. I updated to 0.5.1 and links are fixed. Thanks!
