### ISSUE TITLE
Error 403 Upload icon

### ISSUE THREAD

**Issue by charizzrd** [yariplus/nodebb-plugin-featured-topics-extended#44]
Error when adding icon to tittle

I use Nodebb v1.17.2

Does it give this error in the new version?

**Comment by yariplus** [comment]
I don't think it's caused by this plugin, I wasn't able to reproduce.

**Comment by charizzrd** [comment]
Unfortunately, it's caused by this plugin I tested on 2 different sites and the site where this plugin is installed gave an error

**Comment by charizzrd** [comment]
and I think it would be nice if the added icon blocks were visible

**Comment by charizzrd** [comment]
And I think it would be nice if the added icon was visible in the blocks :)

**Comment by yariplus** [comment]
Is this only occurring when uploading an icon for a new topic?

**Comment by charizzrd** [comment]
yes
