### ISSUE TITLE
Why are the images in the topic not showing? 

### ISSUE THREAD

**Issue by charizzrd** [yariplus/nodebb-plugin-featured-topics-extended#47]
![image](https://user-images.githubusercontent.com/62974390/152117874-331b6127-cc30-4a73-9d79-3da4826c2c5b.png)

On my other site, the first picture in the subject appears, but it does not appear here, what do you think is the problem?

**Comment by yariplus** [comment]
I have this fixed in my dev server. I should have it pushed soon.

**Comment by charizzrd** [comment]
it fixes when i remove the word limit but this time the blocks are too long :) I'm waiting for the new version <3

**Comment by yariplus** [comment]
Pushed latest, let me know.
