### ISSUE TITLE
scout theme looks like porta

### ISSUE THREAD

**Issue by charizzrd** [yariplus/nodebb-plugin-featured-topics-extended#49]
It doesn't matter if I choose both, they look the same. Please bring back my scout theme :)

https://i.ibb.co/7g4gGk9/problem.png

**Comment by yariplus** [comment]
whoops, my bad, try now.

**Comment by charizzrd** [comment]
do you have a chance to fix it like the image resizing is bad in the mobile version?

**Comment by yariplus** [comment]
It could be the thumbnails are too small. Does it still look bad if you remove the thumbnails and post the image inside the topic?

**Comment by charizzrd** [comment]
Yes:( looks like you cut it in half

**Comment by yariplus** [comment]
Could you show a picture of what it should look like?

**Comment by charizzrd** [comment]
[normally like this](https://i.ibb.co/MkMKVnq/Screenshot-20220204-185358-Chrome.jpg)

[make the picture look full like desktop](https://i.ibb.co/QrLMJLF/ghoozt.jpg)

**Comment by yariplus** [comment]
Oh, you want the aspect ratio to remain the same. That's kind of a pain. I'll see what I can do.

**Comment by charizzrd** [comment]
I believe  you 😊 you can do the best

**Comment by charizzrd** [comment]
By the way  please don't forget you carousel  mode 😊😊😊

**Comment by yariplus** [comment]
See how 0.5.10 is for you.

**Comment by charizzrd** [comment]
this is great.. God bless your hands
